cmake_minimum_required(VERSION 3.15)

if(NOT DEFINED ASSIMP_INSTALL_DIR)
    set(ASSIMP_INSTALL_DIR ${CMAKE_SOURCE_DIR}/prebuilt)
    set(ASSIMP_INSTALL_DIR ${CMAKE_SOURCE_DIR}/prebuilt PARENT_SCOPE)
endif()

include(ExternalProject)

ExternalProject_Add(assimp
PREFIX          ${CMAKE_BINARY_DIR}/_deps/assimp
GIT_REPOSITORY  https://github.com/assimp/assimp.git
GIT_TAG         v5.0.1
GIT_SHALLOW     ON
UPDATE_DISCONNECTED 1
CMAKE_ARGS      -DCMAKE_INSTALL_PREFIX:PATH=${ASSIMP_INSTALL_DIR}
                -DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT:BOOL=OFF
                -DASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT:BOOL=OFF
                -DBUILD_SHARED_LIBS:BOOL=OFF
                -DASSIMP_BUILD_ASSIMP_TOOLS:BOOL=OFF
                -DASSIMP_BUILD_TESTS:BOOL=OFF
                -DASSIMP_BUILD_FBX_IMPORTER:BOOL=ON
                -DASSIMP_BUILD_OBJ_IMPORTER:BOOL=ON
                -DASSIMP_BUILD_OBJ_EXPORTER:BOOL=ON
                -DASSIMP_LIBRARY_SUFFIX:STRING=
                -DLIBRARY_SUFFIX:STRING=
                -DCMAKE_DEBUG_POSTFIX:STRING=
                -DASSIMP_INJECT_DEBUG_POSTFIX:BOOL=OFF
)
